version: "3.9"
services:
    adguard_home:
        image: "adguard/adguardhome"
        volumes:
            - "${PWD}/work:/opt/adguard/work"
            - "${PWD}/conf:/opt/adguard/conf"
        ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "80:80/tcp"
            - "3000:3000/tcp"
